from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("admins",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("email",sa.String(255),nullable=False,unique=True),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("role",sa.String(30),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)))
    op.create_table("exams",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("title",sa.String(255),nullable=False),sa.Column("description",sa.Text()),sa.Column("duration_seconds",sa.Integer(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("number_of_questions",sa.Integer(),nullable=False),sa.Column("randomize_questions",sa.Boolean(),nullable=False),sa.Column("randomize_options",sa.Boolean(),nullable=False),sa.Column("one_attempt_only",sa.Boolean(),nullable=False),sa.Column("show_correct_answer_immediately",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("closed_at",sa.DateTime(timezone=True)))
    op.create_table("students",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(255),nullable=False),sa.Column("whatsapp_number",sa.String(40),nullable=False,unique=True),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)))
    op.create_table("questions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("exam_id",sa.Integer(),sa.ForeignKey("exams.id",ondelete="CASCADE"),nullable=False),sa.Column("question_text",sa.Text(),nullable=False),sa.Column("order_index",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)))
    op.create_table("options",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("question_id",sa.Integer(),sa.ForeignKey("questions.id",ondelete="CASCADE"),nullable=False),sa.Column("option_text",sa.String(1000),nullable=False),sa.Column("is_correct",sa.Boolean(),nullable=False),sa.Column("order_index",sa.Integer(),nullable=False),sa.UniqueConstraint("question_id","option_text",name="uq_question_option_text"))
    op.create_table("exam_attempts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("exam_id",sa.Integer(),sa.ForeignKey("exams.id"),nullable=False),sa.Column("student_id",sa.Integer(),sa.ForeignKey("students.id"),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("score",sa.Integer(),nullable=False),sa.Column("total_questions",sa.Integer(),nullable=False),sa.Column("correct_answers",sa.Integer(),nullable=False),sa.Column("wrong_answers",sa.Integer(),nullable=False),sa.Column("percentage",sa.Float(),nullable=False),sa.Column("completion_seconds",sa.Integer()),sa.Column("final_rank",sa.Integer()))
    op.create_table("attempt_questions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("attempt_id",sa.Integer(),sa.ForeignKey("exam_attempts.id",ondelete="CASCADE"),nullable=False),sa.Column("question_id",sa.Integer(),sa.ForeignKey("questions.id"),nullable=False),sa.Column("position",sa.Integer(),nullable=False),sa.UniqueConstraint("attempt_id","question_id",name="uq_attempt_question"),sa.UniqueConstraint("attempt_id","position",name="uq_attempt_position"))
    op.create_table("attempt_options",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("attempt_id",sa.Integer(),sa.ForeignKey("exam_attempts.id",ondelete="CASCADE"),nullable=False),sa.Column("question_id",sa.Integer(),sa.ForeignKey("questions.id"),nullable=False),sa.Column("option_id",sa.Integer(),sa.ForeignKey("options.id"),nullable=False),sa.Column("position",sa.Integer(),nullable=False),sa.UniqueConstraint("attempt_id","question_id","option_id",name="uq_attempt_option"),sa.UniqueConstraint("attempt_id","question_id","position",name="uq_attempt_option_position"))
    op.create_table("attempt_answers",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("attempt_id",sa.Integer(),sa.ForeignKey("exam_attempts.id",ondelete="CASCADE"),nullable=False),sa.Column("question_id",sa.Integer(),sa.ForeignKey("questions.id"),nullable=False),sa.Column("selected_option_id",sa.Integer(),sa.ForeignKey("options.id"),nullable=False),sa.Column("is_correct",sa.Boolean(),nullable=False),sa.Column("answered_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("attempt_id","question_id",name="uq_attempt_answer"))
    op.create_table("processed_webhooks",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("message_id",sa.String(255),nullable=False,unique=True),sa.Column("processed_at",sa.DateTime(timezone=True)))
def downgrade():
    for t in ["processed_webhooks","attempt_answers","attempt_options","attempt_questions","exam_attempts","options","questions","students","exams","admins"]: op.drop_table(t)
